[hyprland.desktop]
hostnames = ["acer-revo-mini-pc", "revo-rb610"]
include = "desktop.conf"

[hyprland.dell_laptop]
hostnames = ["dell-7430", "dell7430"]
include = "laptop.conf"
monitor = "eDP-1, 1920x1080@60, 0x0, 1.4"
gdk_scale = "1.4"
touchpad_natural_scroll = true
touchpad_scroll_factor = 0.4

[hyprland.macbook_air]
hostnames = ["macbook-air-2015", "macbook-air"]
include = "macbook-air.conf"
monitor = "eDP-1, preferred, auto, 1"
gdk_scale = "1"
touchpad_natural_scroll = true
touchpad_scroll_factor = 0.4
unbinds = ["SUPER, code:61", "SUPER ALT, code:61"]
binds = [
  "SUPER, code:61, Cycle MacBook Air scaling, exec, $HOME/.local/bin/kc-hyprland-monitor-scaling-cycle",
  "SUPER ALT, code:61, Cycle MacBook Air scaling backwards, exec, $HOME/.local/bin/kc-hyprland-monitor-scaling-cycle --reverse",
]
