# Shared personal Hyprland configuration.

# Shell scripts bindings
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, Z
unbind = SUPER SHIFT, U
unbind = SUPER SHIFT, I
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, semicolon
bindd = SUPER SHIFT, P, Project Launcher, exec, $HOME/.local/bin/kc-project-launch
bindd = SUPER SHIFT, Z, Session Launcher, exec, $HOME/.local/bin/kc-project-launch-active
bindd = SUPER SHIFT, U, Bookmark Launcher, exec, $HOME/.local/bin/kc-bookmark-launch
bindd = SUPER SHIFT, I, Cheatsheet Launcher, exec, $HOME/.local/bin/kc-cheatsheet-launch
bindd = SUPER SHIFT, W, Web Search, exec, $HOME/.local/bin/kc-search-launch
bindd = SUPER SHIFT, semicolon, Git Repo Status, exec, $HOME/.local/bin/kc-git-repo-status

# More bindings
unbind = SUPER SHIFT, B
bindd = SUPER SHIFT, B, Brave, exec, omarchy-launch-or-focus brave-browser "uwsm-app -- brave"
unbind = SUPER SHIFT, K
bindd = SUPER SHIFT, K, KeePass, exec, omarchy-launch-or-focus keepassxc "uwsm-app -- keepassxc"
unbind = SUPER SHIFT, V
bindd = SUPER SHIFT, V, Visual Studio Code, exec, omarchy-launch-or-focus code "uwsm-app -- code"
unbind = SUPER SHIFT, Y
bindd = SUPER SHIFT, Y, Yazi, exec, omarchy-launch-or-focus yazi "omarchy-launch-tui yazi"
unbind = SUPER SHIFT, C
bindd = SUPER SHIFT, C, Chromium, exec, omarchy-launch-or-focus chromium "uwsm-app -- chromium"
unbind = SUPER SHIFT, D
bindd = SUPER SHIFT, D, DBeaver, exec, omarchy-launch-or-focus DBeaver "uwsm-app -- dbeaver"

# Custom window rules for my workflow
windowrule = match:class code, workspace 2
windowrule = match:class cursor, workspace 2
windowrule = match:class brave-browser, workspace 3
windowrule = match:class obsidian, workspace 6
windowrule = workspace 13, match:class ^org\.omarchy\.yazi$
windowrule = match:title ^Yazi:, workspace 13
windowrule = match:class chromium, workspace 4
windowrule = match:class DBeaver, workspace 5
windowrule = workspace 14, match:class ^(org.keepassxc.KeePassXC|keepassxc)$
windowrule = workspace 14, match:initial_class ^(org.keepassxc.KeePassXC|keepassxc)$

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
}

animations {
    enabled = no
}
