theme = "omarchy"

[editor]
cursorline = true
line-number = "relative"
# scrolloff = 999 # keeps cursor in the middle
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.soft-wrap]
enable = true

[keys.normal]
C-y = [
  ":sh rm -f /tmp/files2open",
  ":set mouse false",
  ":insert-output yazi \"%{buffer_name}\" --chooser-file=/tmp/files2open",
  ":redraw",
  ":set mouse true",
  ":open /tmp/files2open",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  ":buffer-close! /tmp/files2open",
]
